### ISSUE TITLE
Mods wants to run with Java 17..?

### ISSUE THREAD

**Issue by onkoe** [mineLdiver/OptiBabric#5]
When running the game using the provided "babric-b1.7.3" profile and Java 8, I get the following error: 

`The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE... (Java 1.8...)`

Here's the full log:

```
Prism Launcher version: 7.2 (flatpak)


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.159.49, 108.138.159.59, 108.138.159.104, 108.138.159.88]

session.minecraft.net resolves to:
    [13.107.246.57, 13.107.213.57, 2620:1ec:bdf::57, 2620:1ec:46::57]

textures.minecraft.net resolves to:
    [13.107.213.57, 13.107.246.57, 2620:1ec:46::57, 2620:1ec:bdf::57]

api.mojang.com resolves to:
    [13.107.213.57, 13.107.246.57, 2620:1ec:46::57, 2620:1ec:bdf::57]


Minecraft folder is:
/home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft


Java path is:
/app/jdk/8/jre/bin/java


Java is version 1.8.0_372, using 64 (amd64) architecture, from Oracle Corporation.


AMD Ryzen 7 5800X 8-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] (rev c0)

Subsystem: Tul Corporation / PowerColor Device 2419

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.4 (git-8b0202e4b4)

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/natives

Traits:
traits noapplet
traits legacyLaunch
traits texturepacks

Libraries:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-babric.1/lwjgl-2.9.4-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-babric.1/lwjgl_util-2.9.4-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/log4j-config/1.0.0/log4j-config-1.0.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/intermediary/b1.7.3/intermediary-b1.7.3.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/fabric-loader/0.14.19-babric.1/fabric-loader-0.14.19-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-babric.1/lwjgl-platform-2.9.4-babric.1-natives-linux.jar

Mods:
  [✘] Apron-1.0.0.jar (disabled)
  [✘] b1.7.3 BetaTweaks v1.2.2 CLIENT.zip (disabled)
  [✘] b1.7.3_ChangeTexturePackIngame.zip (disabled)
  [✔] beta_OptiFine_1.7.3_HD_MT_G2
  [✘] cursed-legacy-api-1.1.0.jar (disabled)
  [✘] FontFixer-b1.7.3-1-Fabric.jar (disabled)
  [✘] mod-loading-screen-1.0.2.jar (disabled)
  [✘] Modern_Tooltips_Mod_for_Beta_1.7.3.zip (disabled)
  [✘] mojangfix-0.5.1.jar (disabled)
  [✘] MouseTweaks-ModLoader-mcb1.7.3-2.7.2.jar (disabled)
  [✔] optibabric-1.0.0
  [✘] smoothbeta_1.1.2~client.zip (disabled)

Params:
  --username  --session  --gameDir /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft --assetsDir /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java Arguments:
[-Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 2125


Could not find Minecraft folder field
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[17:48:37] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft Beta 1.7.3 with Fabric Loader 0.14.19-babric.1
[17:48:37] [main/INFO] (FabricLoader) Loading 5 mods:
	- fabricloader 0.14.19-babric.1
	- java 8
	- minecraft 1.0.0-beta.7.3
	- optifabric 1.0.0
	   \-- mm 2.3
[17:48:37] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
Exception caught from launcher
java.lang.RuntimeException: Error creating Mixin config optifabric.mixins.json for mod optifabric
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.legacy.LegacyLauncher.launch(LegacyLauncher.java:123)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config optifabric.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.4 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by mineLdiver** [comment]
Yes. All babric mods require Java 17, including StationAPI, SmoothBeta, etc.

**Comment by onkoe** [comment]
Interesting, thank you! Any chance you know where this error comes from? No mods are loaded - it's only Babric...

```
Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.
```

I'm not really sure where to start looking at problems like this. The system library assertion failure makes me think that it's something to do with my Java distribution. Do you think an alternative to OpenJDK, like Amazon's Corretto, would do any better?

Full log:

```
Prism Launcher version: 7.2 (flatpak)


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.138.159.59, 108.138.159.88, 108.138.159.49, 108.138.159.104]

session.minecraft.net resolves to:
    [13.107.213.57, 13.107.246.57, 2620:1ec:bdf::57, 2620:1ec:46::57]

textures.minecraft.net resolves to:
    [13.107.246.57, 13.107.213.57, 2620:1ec:bdf::57, 2620:1ec:46::57]

api.mojang.com resolves to:
    [13.107.246.57, 13.107.213.57, 2620:1ec:46::57, 2620:1ec:bdf::57]


Minecraft folder is:
/home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft


Java path is:
/app/jdk/17/bin/java


Java is version 17.0.7, using 64 (amd64) architecture, from Flathub.


AMD Ryzen 7 5800X 8-Core Processor
Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M] (rev c0)

Subsystem: Tul Corporation / PowerColor Device 2419

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.4 (git-8b0202e4b4)

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/natives

Traits:
traits texturepacks
traits legacyLaunch
traits noapplet

Libraries:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-babric.1/lwjgl-2.9.4-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-babric.1/lwjgl_util-2.9.4-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/log4j-config/1.0.0/log4j-config-1.0.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/intermediary/b1.7.3/intermediary-b1.7.3.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/babric/fabric-loader/0.14.19-babric.1/fabric-loader-0.14.19-babric.1.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/b1.7.3/minecraft-b1.7.3-client.jar

Native libraries:
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-babric.1/lwjgl-platform-2.9.4-babric.1-natives-linux.jar

Mods:
  [✘] Apron-1.0.0.jar (disabled)
  [✘] b1.7.3 BetaTweaks v1.2.2 CLIENT.zip (disabled)
  [✘] beta_OptiFine_1.7.3_HD_MT_G2.zip (disabled)
  [✘] FontFixer-b1.7.3-1-Fabric.jar (disabled)
  [✘] Modern_Tooltips_Mod_for_Beta_1.7.3.zip (disabled)
  [✘] mojangfix-0.5.1.jar (disabled)
  [✘] MouseTweaks-ModLoader-mcb1.7.3-2.7.2.jar (disabled)
  [✘] optibabric-1.0.0.jar (disabled)
  [✘] smoothbeta_1.1.2~client.zip (disabled)

Params:
  --username  --session  --gameDir /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft --assetsDir /home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/babric-b1.7.3/.minecraft/resources

Window size: 854 x 480

Launcher: legacy

Java major version is incompatible. Things might break.
Java Arguments:
[-Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 271


Could not find Minecraft folder field
[18:04:54] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft Beta 1.7.3 with Fabric Loader 0.14.19-babric.1
[18:04:54] [main/INFO] (FabricLoader) Loading 3 mods:
	- fabricloader 0.14.19-babric.1
	- java 17
	- minecraft 1.0.0-beta.7.3
[18:04:54] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/barrett/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
16 achievements
151 recipes
Setting user: smx, token:<ACCESS TOKEN>:<PROFILE ID>
Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.
```

**Comment by mineLdiver** [comment]
Yeah, you're most likely right. I'd recommend trying Eclipse Temurin. Usually works the best for resolving weird issues like this.

**Comment by onkoe** [comment]
Thanks for the quick reply! I tried Temurin, and while it didn't fix anything, it gave me a different library error: 

```
/run/user/1000/doc/df751699/java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
Process exited with code 127.
```

Anyways... I think I'll try some different configurations and let you know if I find one that works. Again, thank you so much for the assistance! :)

**Comment by mineLdiver** [comment]
According to a [quick google search](https://www.thegeekdiary.com/error-while-loading-shared-libraries-libjli-so-cannot-open-shared-object-file-no-such-file-or-directory-java-version-error-on-startup/), I'd guess this is related to flatpak sandboxing. Not much I know about that, unfortunately.

**Comment by onkoe** [comment]
Update - Corretto works great! Make sure to share the necessary system libraries if you're running in Flatpak. Flatseal was really helpful for this.

Thank you for the cool project, by the way! I love having a modern (ancient) version of Minecraft..!

![image](https://github.com/mineLdiver/OptiBabric/assets/66580279/0f0ab62e-caf2-4c4e-b480-14012052c2f5)

**Comment by mineLdiver** [comment]
Ah, glad to know you've fixed it. Enjoy!
