### ISSUE TITLE
incompatible with station api

### ISSUE THREAD

**Issue by kianfakheriaghdam** [mineLdiver/OptiBabric#8]
Station API: 2.0-alpha1.1
Optifine: HD G (the only version i was able to download)

Minecraft is stuck in background when i have these two with each other (Using no other mods).

It loads fine with OptiBabric & Station API without Optifine. The issue occurs when I also add Optifine

I checked the logs & it says:
```
[11:59:37] [AWT-EventQueue-0/ERROR] (FabricLoader/Mixin) Mixin apply for mod (unknown) failed optifabric.compat.arsenic.mixins.json:BedRendererMixin from mod (unknown) -> net.minecraft.class_13: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -> optifabric.compat.arsenic.mixins.json:BedRendererMixin from mod (unknown) -> Plugin Post-Application]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -> optifabric.compat.arsenic.mixins.json:BedRendererMixin from mod (unknown) -> Plugin Post-Application]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1286) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.mine_diver.spasm.impl.MixinTransformerDelegate.transformClassBytes(MixinTransformerDelegate.java:16) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.mine_diver.spasm.impl.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:40) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_579.<init>(class_579.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_92.<init>(class_92.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_594.<init>(class_594.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftApplet$class_641.<init>(MinecraftApplet.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:34) ~[minecraft-b1.7.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletLauncher.init(AppletLauncher.java:138) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletFrame.launch(AppletFrame.java:125) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletMain.run(AppletMain.java:44) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.IllegalStateException: Cannot find shim method stationapi_bed_captureTexture1(Lnet/minecraft/class_17;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_67;IIIFFFFFFFFFFFFFFFFFI)V in net/modificationstation/stationapi/mixin/arsenic/client/block/BedRendererMixin
	at me.modmuss50.optifabric.api.mixin.InterceptingMixinPlugin.lambda$postApply$2(InterceptingMixinPlugin.java:122) ~[optibabric-1.2.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at me.modmuss50.optifabric.api.mixin.InterceptingMixinPlugin.postApply(InterceptingMixinPlugin.java:118) ~[optibabric-1.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.postApply(PluginHandle.java:189) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.postApply(MixinInfo.java:1372) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1275) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	... 35 more
[11:59:37] [AWT-EventQueue-0/ERROR] (FabricLoader) Uncaught exception in thread "AWT-EventQueue-0"
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_13 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_579.<init>(class_579.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_92.<init>(class_92.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_594.<init>(class_594.java:45) ~[client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:155) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftApplet$class_641.<init>(MinecraftApplet.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftApplet.init(MinecraftApplet.java:34) ~[minecraft-b1.7.3-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletLauncher.init(AppletLauncher.java:138) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletFrame.launch(AppletFrame.java:125) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.applet.AppletMain.run(AppletMain.java:44) ~[fabric-loader-0.14.24-babric.1.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.mine_diver.spasm.impl.MixinTransformerDelegate.transformClassBytes(MixinTransformerDelegate.java:16) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.mine_diver.spasm.impl.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:40) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 26 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [optifabric.compat.arsenic.mixins.json:BedRendererMixin from mod (unknown)] from phase [DEFAULT] in config [optifabric.compat.arsenic.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.mine_diver.spasm.impl.MixinTransformerDelegate.transformClassBytes(MixinTransformerDelegate.java:16) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.mine_diver.spasm.impl.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:40) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 26 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded IllegalStateException whilst transforming the mixin class: [PostApply Phase -> optifabric.compat.arsenic.mixins.json:BedRendererMixin from mod (unknown) -> Plugin Post-Application]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1286) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.mine_diver.spasm.impl.MixinTransformerDelegate.transformClassBytes(MixinTransformerDelegate.java:16) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.mine_diver.spasm.impl.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:40) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 26 more
Caused by: java.lang.IllegalStateException: Cannot find shim method stationapi_bed_captureTexture1(Lnet/minecraft/class_17;IIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/class_67;IIIFFFFFFFFFFFFFFFFFI)V in net/modificationstation/stationapi/mixin/arsenic/client/block/BedRendererMixin
	at me.modmuss50.optifabric.api.mixin.InterceptingMixinPlugin.lambda$postApply$2(InterceptingMixinPlugin.java:122) ~[optibabric-1.2.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at me.modmuss50.optifabric.api.mixin.InterceptingMixinPlugin.postApply(InterceptingMixinPlugin.java:118) ~[optibabric-1.2.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.postApply(PluginHandle.java:189) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.postApply(MixinInfo.java:1372) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1275) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:346) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.mine_diver.spasm.impl.MixinTransformerDelegate.transformClassBytes(MixinTransformerDelegate.java:16) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.mine_diver.spasm.impl.MixinTransformerHook.transformClassBytes(MixinTransformerHook.java:40) ~[spasm-0.2.2-367ce6aac3b8e096.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.24-babric.1.jar:?]
	... 26 more
```

**Comment by mineLdiver** [comment]
This is an issue with the alpha releases of StAPI and is already work in progress. Currently I just need to figure out some vanilla textures being incorrect when running OptiFine with StAPI and it should be good to go.

**Comment by CuteistCat** [comment]
btw use https://optifine.net/adloadx?f=beta_OptiFine_1.7.3_HD_MT_G2.zip to get OF HD MT G2
