### ISSUE TITLE
Could not rename the file

### ISSUE THREAD

**Issue by tomokao** [mineLdiver/OptiBabric#9]
This error shows on startup:

```
[main/ERROR] (FabricLoader/Mixin) Error encountered during mixin config postInit step 'mixins.mm.json' from mod 'mm': Could not rename the file <snip>/.minecraft/.optifabric/optifine-remapped.jar to /tmp/optifine-remapped.jar4862404595883570519.tmp
java.lang.RuntimeException: Could not rename the file <snip>/.minecraft/.optifabric/optifine-remapped.jar to /tmp/optifine-remapped.jar4862404595883570519.tmp
	at me.modmuss50.optifabric.mod.OptifabricSetup.addIcon(OptifabricSetup.java:191) ~[optibabric-1.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.getRemappedOptifine(OptifabricSetup.java:173) ~[optibabric-1.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:60) ~[optibabric-1.2.jar:?]
```

**Comment by mineLdiver** [comment]
That's odd. What OS are you on?

**Comment by erentar** [comment]
I also have this problem
On Fedora 40 with adoptium 17

```
[03:16:06] [main/ERROR] (FabricLoader/Mixin) Error encountered during mixin config postInit step 'mixins.mm.json' from mod 'mm': Could not rename the file /home/user/PrismLauncher8.4/instances/babric-b1.7.3/.minecraft/.optifabric/optifine-remapped.jar to /tmp/optifine-remapped.jar13963234593278222146.tmp
java.lang.RuntimeException: Could not rename the file /home/user/PrismLauncher8.4/instances/babric-b1.7.3/.minecraft/.optifabric/optifine-remapped.jar to /tmp/optifine-remapped.jar13963234593278222146.tmp
	at me.modmuss50.optifabric.mod.OptifabricSetup.addIcon(OptifabricSetup.java:191) ~[optibabric-1.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.getRemappedOptifine(OptifabricSetup.java:173) ~[optibabric-1.2.jar:?]
	at me.modmuss50.optifabric.mod.OptifabricSetup.run(OptifabricSetup.java:60) ~[optibabric-1.2.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at com.chocohead.mm.Plugin.getMixins(Plugin.java:340) ~[mm-2.3-dea3eead7ecec716.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.getMixins(PluginHandle.java:128) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:796) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.14.24-babric.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.24-babric.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.24-babric.1.jar:?]
	at org.prismlauncher.legacy.LegacyLauncher.launch(LegacyLauncher.java:123) [NewLaunchLegacy.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

**Comment by Trhod17** [comment]
The simple fix is to run this command on the .fabric directory in instances/{instance name here}/.minecraft 

chmod -R 755 .fabric/
